language:
  python

python:
  - 3.6

install:
  - ./tools/generate_key_pair.sh
  - pip install --upgrade -r requirements.dev.txt
  - export PRIVATE_KEY=`cat private.pem`

script:
  - export
  - pylama auth
  - python -m pytest tests -sv --cov=auth

after_success:
  - coveralls
